version: '3.3'
services:
  mysql:
    image: sahay/sql:f5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always
  Php72cli:
    image: sahay/php:f5
    links:
      - mysql
  Apache:
    image: sahay/apache:f5
    ports:
      - "80:80"
      - "443:443"
    links:
      - Php72cli
      - mysql