version: '3'

services:
 mysql:
  restart: always
  image: kraskobohdan/lamp:mysql
  ports:
   - "3306:3306"
  environment:
   - MYSQL_DATABASE=db
   - MYSQL_USER=user
   - MYSQL_PASSWORD=user
   - MYSQL_ROOT_PASSWORD=root
 php:
  image: kraskobohdan/lamp:php
  ports:
   - "9000:9000"
  links:
   - mysql
 nginx:
  image: kraskobohdan/lamp:nginx
  ports:
   - "8080:80"
  links:
   - php
