version: '3'

services:
    apache:
      container_name: php-apache
      image: rdev7/php-apache
      ports:
        - 80:80
      volumes:
        - ./src:/var/www/html/
    
    db:
      container_name: project-db
      image: rdev7/mysql
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: userdb
        MYSQL_USER: testuser
        MYSQL_PASSWORD: testuser
