version: '3.8'
 
services:
 
  httpd: 
    image: zaluzh/httpd 
    depends_on: 
      - php 
    ports:
      - "8080:80"
 
  php: 
    image: zaluzh/php:third 

  mysql: 
    image: zaluzh/mysql:second 
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: 'db' 
      MYSQL_USER: 'user' 
      MYSQL_PASSWORD: 'password' 
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always 
    depends_on: 
      - httpd
