version: '3.8'

services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8080:8080